import { CategoryConfig } from "@databiosphere/findable-ui/lib/common/categories/config/types";
import { mapSelectCategoryValue } from "../../../../app/config/utils";
import { SiteConfig } from "../../../common/entities";
import { HCA_DCP_CATEGORY_KEY, HCA_DCP_CATEGORY_LABEL } from "../../category";
import { mapAccessibleValue, mapDataUseRestrictionValue } from "./utils";

export const CATEGORY_CONFIG: Record<string, CategoryConfig> = {
  ACCESSIBLE: {
    key: HCA_DCP_CATEGORY_KEY.ACCESSIBLE,
    label: HCA_DCP_CATEGORY_LABEL.ACCESSIBLE,
    mapSelectCategoryValue: mapSelectCategoryValue(mapAccessibleValue),
  },
  BIOLOGICAL_SEX: {
    key: HCA_DCP_CATEGORY_KEY.BIOLOGICAL_SEX,
    label: HCA_DCP_CATEGORY_LABEL.BIOLOGICAL_SEX,
  },
  BIONETWORK_NAME: {
    key: HCA_DCP_CATEGORY_KEY.BIONETWORK_NAME,
    label: HCA_DCP_CATEGORY_LABEL.BIONETWORK_NAME,
  },
  CONTACT_NAME: {
    chart: { enable: false },
    key: HCA_DCP_CATEGORY_KEY.CONTACT_NAME,
    label: HCA_DCP_CATEGORY_LABEL.CONTACT_NAME,
  },
  CONTENT_DESCRIPTION: {
    key: HCA_DCP_CATEGORY_KEY.CONTENT_DESCRIPTION,
    label: HCA_DCP_CATEGORY_LABEL.CONTENT_DESCRIPTION,
  },
  DATA_USE_RESTRICTION: {
    key: HCA_DCP_CATEGORY_KEY.DATA_USE_RESTRICTION,
    label: HCA_DCP_CATEGORY_LABEL.DATA_USE_RESTRICTION,
    mapSelectCategoryValue: mapSelectCategoryValue(mapDataUseRestrictionValue),
  },
  DEVELOPMENT_STAGE: {
    chart: { enable: false },
    key: HCA_DCP_CATEGORY_KEY.DEVELOPMENT_STAGE,
    label: HCA_DCP_CATEGORY_LABEL.DEVELOPMENT_STAGE,
  },
  DONOR_DISEASE: {
    chart: { enable: false },
    key: HCA_DCP_CATEGORY_KEY.DONOR_DISEASE,
    label: HCA_DCP_CATEGORY_LABEL.DONOR_DISEASE,
  },
  FILE_FORMAT: {
    key: HCA_DCP_CATEGORY_KEY.FILE_FORMAT,
    label: HCA_DCP_CATEGORY_LABEL.FILE_FORMAT,
  },
  FILE_SOURCE: {
    key: HCA_DCP_CATEGORY_KEY.FILE_SOURCE,
    label: HCA_DCP_CATEGORY_LABEL.FILE_SOURCE,
  },
  GENUS_SPECIES: {
    key: HCA_DCP_CATEGORY_KEY.GENUS_SPECIES,
    label: HCA_DCP_CATEGORY_LABEL.GENUS_SPECIES,
  },
  INSTITUTION: {
    chart: { enable: false },
    key: HCA_DCP_CATEGORY_KEY.INSTITUTION,
    label: HCA_DCP_CATEGORY_LABEL.INSTITUTION,
  },
  INSTRUMENT_MANUFACTURER_MODEL: {
    key: HCA_DCP_CATEGORY_KEY.INSTRUMENT_MANUFACTURER_MODEL,
    label: HCA_DCP_CATEGORY_LABEL.INSTRUMENT_MANUFACTURER_MODEL,
  },
  LIBRARY_CONSTRUCTION_APPROACH: {
    key: HCA_DCP_CATEGORY_KEY.LIBRARY_CONSTRUCTION_METHOD,
    label: HCA_DCP_CATEGORY_LABEL.LIBRARY_CONSTRUCTION_METHOD,
  },
  MODEL_ORGAN: {
    key: HCA_DCP_CATEGORY_KEY.MODEL_ORGAN,
    label: HCA_DCP_CATEGORY_LABEL.MODEL_ORGAN,
  },
  NUCLEIC_ACID_SOURCE: {
    key: HCA_DCP_CATEGORY_KEY.NUCLEIC_ACID_SOURCE,
    label: HCA_DCP_CATEGORY_LABEL.NUCLEIC_ACID_SOURCE,
  },
  ORGAN_PART: {
    key: HCA_DCP_CATEGORY_KEY.ORGAN_PART,
    label: HCA_DCP_CATEGORY_LABEL.ORGAN_PART,
  },
  PAIRED_END: {
    key: HCA_DCP_CATEGORY_KEY.PAIRED_END,
    label: HCA_DCP_CATEGORY_LABEL.PAIRED_END,
  },
  PRESERVATION_METHOD: {
    key: HCA_DCP_CATEGORY_KEY.PRESERVATION_METHOD,
    label: HCA_DCP_CATEGORY_LABEL.PRESERVATION_METHOD,
  },
  PROJECT_TITLE: {
    chart: { enable: false },
    key: HCA_DCP_CATEGORY_KEY.PROJECT_TITLE,
    label: HCA_DCP_CATEGORY_LABEL.PROJECT_TITLE,
  },
  SAMPLE_ENTITY_TYPE: {
    key: HCA_DCP_CATEGORY_KEY.SAMPLE_ENTITY_TYPE,
    label: HCA_DCP_CATEGORY_LABEL.SAMPLE_ENTITY_TYPE,
  },
  SELECTED_CELL_TYPE: {
    key: HCA_DCP_CATEGORY_KEY.SELECTED_CELL_TYPE,
    label: HCA_DCP_CATEGORY_LABEL.SELECTED_CELL_TYPE,
  },
  SPECIMEN_DISEASE: {
    key: HCA_DCP_CATEGORY_KEY.SPECIMEN_DISEASE,
    label: HCA_DCP_CATEGORY_LABEL.SPECIMEN_DISEASE,
  },
  SPECIMEN_ORGAN: {
    key: HCA_DCP_CATEGORY_KEY.ANATOMICAL_ENTITY,
    label: HCA_DCP_CATEGORY_LABEL.ANATOMICAL_ENTITY,
  },
  WORKFLOW: {
    key: HCA_DCP_CATEGORY_KEY.ANALYSIS_PROTOCOL,
    label: HCA_DCP_CATEGORY_LABEL.ANALYSIS_PROTOCOL,
  },
} as const;

export const CATEGORY_GROUP_CONFIG: SiteConfig["categoryGroupConfig"] = {
  categoryGroups: [
    {
      categoryConfigs: [
        CATEGORY_CONFIG.PROJECT_TITLE,
        CATEGORY_CONFIG.CONTACT_NAME,
        CATEGORY_CONFIG.INSTITUTION,
        CATEGORY_CONFIG.BIONETWORK_NAME,
        CATEGORY_CONFIG.ACCESSIBLE,
        CATEGORY_CONFIG.DATA_USE_RESTRICTION,
      ],
      label: "Project",
    },
    {
      categoryConfigs: [
        CATEGORY_CONFIG.BIOLOGICAL_SEX,
        CATEGORY_CONFIG.DEVELOPMENT_STAGE,
        CATEGORY_CONFIG.DONOR_DISEASE,
        CATEGORY_CONFIG.GENUS_SPECIES,
      ],
      label: "Donor",
    },
    {
      categoryConfigs: [
        CATEGORY_CONFIG.SPECIMEN_ORGAN,
        CATEGORY_CONFIG.ORGAN_PART,
        CATEGORY_CONFIG.PRESERVATION_METHOD,
        CATEGORY_CONFIG.MODEL_ORGAN,
        CATEGORY_CONFIG.SAMPLE_ENTITY_TYPE,
        CATEGORY_CONFIG.SELECTED_CELL_TYPE,
        CATEGORY_CONFIG.SPECIMEN_DISEASE,
      ],
      label: "Sample",
    },
    {
      categoryConfigs: [
        CATEGORY_CONFIG.WORKFLOW,
        CATEGORY_CONFIG.INSTRUMENT_MANUFACTURER_MODEL,
        CATEGORY_CONFIG.LIBRARY_CONSTRUCTION_APPROACH,
        CATEGORY_CONFIG.NUCLEIC_ACID_SOURCE,
        CATEGORY_CONFIG.PAIRED_END,
      ],
      label: "Protocol",
    },
    {
      categoryConfigs: [
        CATEGORY_CONFIG.CONTENT_DESCRIPTION,
        CATEGORY_CONFIG.FILE_FORMAT,
        CATEGORY_CONFIG.FILE_SOURCE,
      ],
      label: "File",
    },
  ],
  key: "hca-dcp",
};
