
stages:
  - test
  - build
  - deploy

# Build Jobs
# Build Job Template
.build_template: &build_template
  image: clevercanary/ng-cli-karma-python3:13.2.5
  stage: build
  before_script:
    - npm -v
    - node -v
    - cd spa
    - npm install
    - cd ..
    - cd scripts
    - npm install
    - cd ..
  artifacts:
      paths:
        - dist
        - maintenance


# Test with Trufflehog
test_trufflehog:
  stage: test
  image: python:3.5
  before_script:
    - pip install trufflehog
  script:
    - trufflehog --regex --rules trufflehog-rules.json --branch main --max_depth 30 --entropy=False https://github.com/HumanCellAtlas/data-browser.git
  except:
    - prod

# Test with karma
test_karma:
  image: clevercanary/ng-cli-karma-python3:13.2.5
  stage: test
  script:
    - cd spa
    - npm install
    - ng test --watch=false
  except:
    - prod

# Develop Build
build_cgl-dev:
  <<: *build_template
  environment:
    name: cgl-dev
  script:
    - export GTM_ID=GTM-M2J5NTJ
    - export GTM_AUTH=CzDpc0__fhyqfREDehPK8Q
    - export GTM_ENV=env-83
    - pwd
    - ./insert-gtm-snippet.sh
    - cd spa
    - npm run build-cgl-dev
    - cd ..
    - cd scripts
    - npm run update-sitemap -- catalog=dcp20
  only:
    - main
build_cgl-ux-dev:
  <<: *build_template
  environment:
    name: cgl-ux-dev
  script:
    - export GTM_ID=GTM-M2J5NTJ
    - export GTM_AUTH=CzDpc0__fhyqfREDehPK8Q
    - export GTM_ENV=env-83
    - pwd
    - ./insert-gtm-snippet.sh
    - cd spa
    - npm run build-cgl-dev
  only:
    - ux-dev

build_lungmap-dev:
  <<: *build_template
  environment:
    name: lungmap-dev
  script:
    - export GTM_ID=GTM-M2J5NTJ
    - export GTM_AUTH=XOKAlpBSltsrm1PKGR-fow
    - export GTM_ENV=env-149
    - pwd
    - ./insert-gtm-snippet.sh
    - cd spa
    - npm run build-lungmap-dev
    - cd ..
    - cd scripts
    - npm run update-sitemap -- catalog=lm2
  only:
    - lungmap-main

########################################
# Deploy Jobs
########################################


# Deploy Job Template
.deploy_template: &deploy_template
  stage: deploy
  image: python:3.5
  before_script:
    - pip install awscli

# Dev Deploy
deploy_cgl-dev:
  <<: *deploy_template
  environment:
    name: cgl-dev
  script:
    - export BUCKET=s3://dev.explore.singlecell.gi.ucsc.edu
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=dist/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws s3 cp $BUCKET/explore/index.html $BUCKET/explore/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
    - aws cloudfront create-invalidation --distribution-id E3562WJBOLN8W8 --paths "/*"
  only:
    - main

# ux-dev deploy
deploy_cgl-ux-dev:
  <<: *deploy_template
  environment:
    name: cgl-ux-dev
  script:
    - export BUCKET=s3://ux-dev.explore.singlecell.gi.ucsc.edu
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=dist/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws s3 cp $BUCKET/explore/index.html $BUCKET/explore/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
    - aws cloudfront create-invalidation --distribution-id E3FFK49Z7TQ60R --paths "/*"
  only:
    - ux-dev


# Lungmap Dev Deploy
deploy_lungmap-dev:
  <<: *deploy_template
  environment:
    name: lungmap-dev
  script:
    - export BUCKET=s3://dev.explore.lungmap.net
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=dist/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws s3 cp $BUCKET/explore/index.html $BUCKET/explore/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
    - aws cloudfront create-invalidation --distribution-id E21CJFOUWO9Q7X --paths "/*"
  only:
    - lungmap-main


