
stages:
  - build
  - deploy

# Build Jobs
# Build Job Template
.build_template: &build_template
  image: node:10.0.0
  stage: build
  before_script:
    - cd spa
    - npm -v
    - npm install
    - cd ..

  artifacts:
      paths:
        - dist

# Develop Build
build_develop:
  <<: *build_template
  environment:
    name: develop
  script:
    - export GTM_ID=GTM-M2J5NTJ
    - export GTM_AUTH=9YN1zUWSooX9gvYK43KPlg
    - export GTM_ENV=env-6
    - pwd
    - ./insert-gtm-snippet.sh
    - cd spa
    - npm run build-develop
  only:
    - develop

# UX-Dev Build
build_ux-dev:
  <<: *build_template
  environment:
    name: ux-dev
  script:
    - export GTM_ID=GTM-M2J5NTJ
    - export GTM_AUTH=V6JsS1EO6wZraCRRVvsrlw
    - export GTM_ENV=env-11
    - pwd
    - ./insert-gtm-snippet.sh
    - cd spa
    - npm run build-ux-dev
  only:
    - ux-dev

# Integration Build
build_integration:
  <<: *build_template
  environment:
    name: integration
  script:
    - export GTM_ID=GTM-M2J5NTJ
    - export GTM_AUTH=idWkz24fhkH__F0XXIBNGA
    - export GTM_ENV=env-8
    - pwd
    - ./insert-gtm-snippet.sh
    - cd spa
    - npm run build-integration
  only:
    - integration

## Staging Build
build_staging:
  <<: *build_template
  environment:
    name: staging
  script:
    - export GTM_ID=GTM-M2J5NTJ
    - export GTM_AUTH=CVR6RDnBikpJoyAEnybSBw
    - export GTM_ENV=env-10
    - pwd
    - ./insert-gtm-snippet.sh
    - cd spa
    - npm run build-staging
  only:
    - staging

########################################
# Deploy Jobs
########################################


# Deploy Job Template
.deploy_template: &deploy_template
  stage: deploy
  image: python:3.5
  before_script:
    - pip install awscli

# Dev Deploy
deploy_develop:
  <<: *deploy_template
  environment:
    name: develop
  script:
    - export BUCKET=s3://dev.explore.data.humancellatlas.org/
    - aws s3 sync --acl public-read dist/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id EDQUW4UP25O4L --paths "/*"
  only:
    - develop

# UX-Dev Deploy
deploy_ux-dev:
  <<: *deploy_template
  environment:
    name: ux-dev
  script:
    - export BUCKET=s3://ux-dev.explore.data.humancellatlas.org/
    - aws s3 sync --acl public-read dist/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E3JWRFLK4O8V1L --paths "/*"
  only:
    - ux-dev


# Integration Deploy
deploy_integration:
  <<: *deploy_template
  environment:
    name: integration
  script:
    - export BUCKET=s3://integration.explore.data.humancellatlas.org/
    - aws s3 sync --acl public-read dist/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E2MB44J9QEJOYP --paths "/*"
  only:
    - integration

## Staging Deploy
deploy_staging:
  <<: *deploy_template
  environment:
    name: staging
  script:
    - export BUCKET=s3://staging.explore.data.humancellatlas.org/
    - aws s3 sync --acl public-read dist/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E38D6Y96QKYO6 --paths "/*"
  only:
    - staging
