
stages:
  - test
  - build
  - deploy

# Build Jobs
# Build Job Template
.build_template: &build_template
  image: node:14.16.0
  stage: build
  before_script:
    - npm -v
    - npm install npm@6.14.11 -g
    - npm -v
    - cd spa
    - npm install
    - cd ..
  artifacts:
      paths:
        - dist
        - maintenance

# Test with Trufflehog
test_trufflehog:
  stage: test
  image: python:3.5
  before_script:
    - pip install trufflehog
  script:
    - trufflehog --regex --rules trufflehog-rules.json --branch prod --max_depth 30 --entropy=False https://github.com/HumanCellAtlas/data-browser.git
  only:
    - prod

# Test with karma
test_karma:
  image: trion/ng-cli-karma
  stage: test
  script:
    - cd spa
    - npm install
    - ng test --watch=false
  only:
    - prod


# Prod Build
build_prod:
  <<: *build_template
  environment:
    name: prod
  script:
    - export GTM_ID=GTM-M2J5NTJ
    - export GTM_AUTH=xm3qglWPEFim7Lb4AxXnsA
    - export GTM_ENV=env-2
    - pwd
    - ./insert-gtm-snippet.sh
    - cd spa
    - npm run build-cgl-dcp2
  only:
    - prod

########################################
# Deploy Jobs
########################################


# Deploy Job Template
.deploy_template: &deploy_template
  stage: deploy
  image: python:3.5
  before_script:
    - pip install awscli

# Prod Deploy
deploy_prod:
  <<: *deploy_template
  environment:
    name: prod
  script:
    - export BUCKET=s3://org-humancellatlas-data-browser-dcp2-prod
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=dist/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws s3 cp $BUCKET/explore/index.html $BUCKET/explore/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
    - aws cloudfront create-invalidation --distribution-id E1LYQC3LZXO7M3 --paths "/*"
  only:
    - prod
