export const ANVIL_CATEGORY_KEY = {
  ACTIVITY_TYPE: "activity_type",
  ANATOMICAL_SITE: "anatomical_site",
  BIOSAMPLE_ID: "biosample_id",
  BIOSAMPLE_TYPE: "biosample_type",
  DATASET_NAME: "title",
  DATA_MODALITY: "data_modality",
  DOCUMENT_ID: "document_id",
  DONOR_ID: "donor_id",
  FILE_FORMAT: "file_format",
  FILE_ID: "file_id",
  FILE_TYPE: "file_type",
  LIBRARY_ID: "library_id",
  LIBRARY_PREPARATION: "prep_material_name",
  ORGANISM_TYPE: "organism_type",
  PHENOTYPIC_SEX: "phenotypic_sex",
  REPORTED_ETHNICITY: "reported_ethnicity",
};

export const ANVIL_CATEGORY_LABEL = {
  ACTIVITY_TYPE: "Activity Type",
  ANATOMICAL_SITE: "Anatomical Site",
  BIOSAMPLE_ID: "BioSample Id",
  BIOSAMPLE_TYPE: "BioSample Type",
  DATASET_NAME: "Dataset Name",
  DATA_MODALITY: "Data Modality",
  DOCUMENT_ID: "Document Id",
  DONOR_ID: "Donor Id",
  FILE_FORMAT: "File Format",
  FILE_ID: "File Id",
  FILE_TYPE: "File Type",
  LIBRARY_ID: "Library Id",
  LIBRARY_PREPARATION: "Library Preparation",
  ORGANISM_TYPE: "Organism Type",
  PHENOTYPIC_SEX: "Phenotypic Sex",
  REPORTED_ETHNICITY: "Reported Ethnicity",
};
