export const ANVIL_CATALOG_COLUMN_NAMES = {
  CONSENT_CODE: "Consent Code",
  CONSENT_CODES: "Consent Codes",
  CONSORTIUM: "Consortium",
  DATA_TYPE: "Data Type",
  DBGAP_ID: "dbGap Id",
  DISEASE_INDICATION: "Disease (indication)",
  PARTICIPANTS: "Participants",
  SIZE_TB: "Size (TB)",
  STUDY: "Study",
  STUDY_DESIGN: "Study Design",
  TERRA_WORKSPACE: "Terra Workspace",
  WORKSPACES: "Workspaces",
};

export const PLURALIZED_METADATA_LABEL = {
  [ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM]: "networks",
  [ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID]: "dbGap ids",
  [ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODES]: "consent codes",
  [ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION]: "diseases",
  [ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE]: "data types",
  [ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN]: "study designs",
  [ANVIL_CATALOG_COLUMN_NAMES.WORKSPACES]: "workspaces",
  [ANVIL_CATALOG_COLUMN_NAMES.STUDY]: "studies",
  [ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODE]: "consent codes",
  [ANVIL_CATALOG_COLUMN_NAMES.TERRA_WORKSPACE]: "workspaces",
};

export const ANVIL_CATALOG_CONSORTIA_PRESELECTED_COLUMNS_BY_NAME = {
  [ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODES]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODES,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODES],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.PARTICIPANTS]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.PARTICIPANTS,
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.SIZE_TB]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.SIZE_TB,
    sortable: true,
  },
};

export const ANVIL_CATALOG_CONSORTIA_SELECTABLE_COLUMNS_BY_NAME = {
  Study: {
    name: "Study",
    pluralizedLabel: "studies",
    sortable: true,
  },
  Workspaces: {
    name: "Workspaces",
    pluralizedLabel: "workspaces",
    sortable: true,
  },
};

export const ANVIL_CATALOG_STUDIES_PRESELECTED_COLUMNS_BY_NAME = {
  [ANVIL_CATALOG_COLUMN_NAMES.STUDY]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.STUDY,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.STUDY],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODES]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODES,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODES],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.PARTICIPANTS]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.PARTICIPANTS,
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.SIZE_TB]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.SIZE_TB,
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.WORKSPACES]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.WORKSPACES,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.WORKSPACES],
    sortable: true,
  },
};

export const ANVIL_CATALOG_STUDIES_SELECTABLE_COLUMNS_BY_NAME = {};

export const ANVIL_CATALOG_WORKSPACES_PRESELECTED_COLUMNS_BY_NAME = {
  [ANVIL_CATALOG_COLUMN_NAMES.TERRA_WORKSPACE]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.TERRA_WORKSPACE,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.TERRA_WORKSPACE],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.STUDY]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.STUDY,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.STUDY],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DBGAP_ID],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.CONSORTIUM],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODE]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODE,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.CONSENT_CODE],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DISEASE_INDICATION],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.DATA_TYPE],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN,
    pluralizedLabel:
      PLURALIZED_METADATA_LABEL[ANVIL_CATALOG_COLUMN_NAMES.STUDY_DESIGN],
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.PARTICIPANTS]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.PARTICIPANTS,
    sortable: true,
  },
  [ANVIL_CATALOG_COLUMN_NAMES.SIZE_TB]: {
    name: ANVIL_CATALOG_COLUMN_NAMES.SIZE_TB,
    sortable: true,
  },
};

export const ANVIL_CATALOG_WORKSPACES_SELECTABLE_COLUMNS_BY_NAME = {};
