/**
 * Set of entity status.
 */
export enum ENTITY_STATUS {
  DEPRECATED = "DEPRECATED",
  DUPLICATE = "DUPLICATE",
  INGEST_IN_PROGRESS = "INGEST_IN_PROGRESS",
  LIVE = "LIVE",
  WITHDRAWN = "WITHDRAWN",
}
