name: hdgar-book
# channels:
#   - defaults
#   - conda-forge
dependencies:
  - pandas
  - numpy
  - matplotlib
  - pip
  - pip:
    - jupyter-book
    - pyppeteer
    - google-auth-oauthlib
    - google-api-python-client
    - google-cloud-bigquery
    - db-dtypes