stages:
  - build_image
  - generate_child_yaml
  - trigger_child

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_PIPELINE_ID

.on_branch_push:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH

build_image:
  extends: .on_branch_push
  stage: build_image
  rules:
    - if: $CI_COMMIT_BRANCH
  script:
    - cd .gitlab
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker build --tag $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

generate_child_yaml:
  extends: .on_branch_push
  stage: generate_child_yaml
  image: $DOCKER_IMAGE:$DOCKER_TAG
  script:
    - cd .gitlab
    - npm ci
    - npx tsc
    - node ci.child.yaml.template.js > ci.child.yaml
  artifacts:
    paths:
      - .gitlab/ci.child.yaml

trigger_child:
  stage: trigger_child
  trigger:
    include:
      - artifact: .gitlab/ci.child.yaml
        job: generate_child_yaml
