export const ANVIL_CMG_CATEGORY_KEY = {
  ACCESSIBLE: "accessible",
  ACTIVITY_ACTIVITY_TYPE: "activities.activity_type",
  ACTIVITY_DATA_MODALITY: "activities.data_modality",
  ACTIVITY_DOCUMENT_ID: "activities.document_id",
  AZUL_FILE_DOWNLOAD: "azulFileDownload",
  BIOSAMPLE_ANATOMICAL_SITE: "biosamples.anatomical_site",
  BIOSAMPLE_BIOSAMPLE_ID: "biosamples.biosample_id",
  BIOSAMPLE_BIOSAMPLE_TYPE: "biosamples.biosample_type",
  BIOSAMPLE_TYPE: "biosample_type",
  DATASET_ACCESSIBLE: "datasets.accessible",
  DATASET_CONSENT_GROUP: "datasets.consent_group",
  DATASET_ID: "datasets.dataset_id",
  DATASET_REGISTERED_ID: "datasets.registered_identifier",
  DATASET_TITLE: "datasets.title",
  DIAGNOSE_DISEASE: "diagnoses.disease",
  DIAGNOSIS_PHENOTYPE: "diagnoses.phenotype",
  DONOR_DONOR_ID: "donors.donor_id",
  DONOR_ORGANISM_TYPE: "donors.organism_type",
  DONOR_PHENOTYPIC_SEX: "donors.phenotypic_sex",
  DONOR_REPORTED_ETHNICITY: "donors.reported_ethnicity",
  DRS_URI: "files.drs_uri",
  FILE_DATA_MODALITY: "files.data_modality",
  FILE_FILE_FORMAT: "files.file_format",
  FILE_FILE_NAME: "files.file_name",
  FILE_FILE_SIZE: "files.file_size",
  FILE_FILE_TYPE: "files.file_type",
  LIBRARY_ID: "library_id",
  PREP_MATERIAL_NAME: "prep_material_name",
};

export const ANVIL_CMG_CATEGORY_LABEL = {
  ACCESSIBLE: "Access",
  ACTIVITY_ACTIVITY_TYPE: "Activity Type",
  ACTIVITY_DATA_MODALITY: "Data Modality",
  ACTIVITY_DOCUMENT_ID: "Document Id",
  AZUL_FILE_DOWNLOAD: " ",
  BIOSAMPLE_ANATOMICAL_SITE: "Anatomical Site",
  BIOSAMPLE_BIOSAMPLE_ID: "BioSample Id",
  BIOSAMPLE_BIOSAMPLE_TYPE: "BioSample Type",
  BIOSAMPLE_TYPE: "BioSample Type",
  DATASET_ACCESSIBLE: "Access",
  DATASET_CONSENT_GROUP: "Consent Group",
  DATASET_ID: "Dataset Name",
  DATASET_REGISTERED_ID: "Identifier",
  DATASET_TITLE: "Dataset",
  DIAGNOSE_DISEASE: "Diagnosis",
  DIAGNOSIS_PHENOTYPE: "Phenotype",
  DONOR_DONOR_ID: "Donor Id",
  DONOR_ORGANISM_TYPE: "Organism Type",
  DONOR_PHENOTYPIC_SEX: "Phenotypic Sex",
  DONOR_REPORTED_ETHNICITY: "Reported Ethnicity",
  DRS_URI: "DRS URI",
  FILE_DATA_MODALITY: "Data Modality",
  FILE_FILE_FORMAT: "File Format",
  FILE_FILE_NAME: "Name",
  FILE_FILE_SIZE: "Size",
  FILE_FILE_TYPE: "File Type",
  LIBRARY_ID: "Library Id",
  PREP_MATERIAL_NAME: "Library Preparation",
};

export const DATASET_RESPONSE = {
  DATASETS: "datasets",
};
