export const HCA_DCP_CATEGORY_KEY = {
  ANALYSIS_PROTOCOL: "workflow",
  ANATOMICAL_ENTITY: "specimenOrgan",
  AZUL_FILE_DOWNLOAD: "azulFileDownload",
  BIOLOGICAL_SEX: "biologicalSex",
  CELL_COUNT: "cellCount",
  CONTACT_NAME: "contactName",
  CONTENT_DESCRIPTION: "contentDescription",
  DEVELOPMENT_STAGE: "developmentStage",
  DONOR_DISEASE: "donorDisease",
  EFFECTIVE_CELL_COUNT: "effectiveCellCount",
  FILE_FORMAT: "fileFormat",
  FILE_NAME: "fileName",
  FILE_SIZE: "fileSize",
  FILE_SOURCE: "fileSource",
  GENUS_SPECIES: "genusSpecies",
  INSTITUTION: "institution",
  INSTRUMENT_MANUFACTURER_MODEL: "instrumentManufacturerModel",
  LABORATORY: "laboratory",
  LIBRARY_CONSTRUCTION_METHOD: "libraryConstructionApproach",
  MATRIX_CELL_COUNT: "matrixCellCount",
  MODEL_ORGAN: "modelOrgan",
  MODIFIED: "modified",
  NUCLEIC_ACID_SOURCE: "nucleicAcidSource",
  ORGAN: "organ",
  ORGAN_PART: "organPart",
  PAIRED_END: "pairedEnd",
  PRESERVATION_METHOD: "preservationMethod",
  PROJECT: "project",
  PROJECT_ID: "projectId",
  PROJECT_TITLE: "projectTitle",
  PUBLICATION_TITLE: "publicationTitle",
  SAMPLE_ENTITY_TYPE: "sampleEntityType",
  SAMPLE_ID: "sampleId",
  SAMPLE_TYPE: "sampleType",
  SELECTED_CELL_TYPE: "selectedCellType",
  SPECIMEN_DISEASE: "specimenDisease",
  SPECIMEN_ORGAN: "specimenOrgan",
  WORKFLOW: "workflow",
} as const;

export const HCA_DCP_CATEGORY_LABEL = {
  ANALYSIS_PROTOCOL: "Analysis Protocol",
  ANATOMICAL_ENTITY: "Anatomical Entity",
  AZUL_FILE_DOWNLOAD: " ",
  BIOLOGICAL_SEX: "Biological Sex",
  CELL_COUNT: "Cell Count Estimate",
  CONTACT_NAME: "Contact Name",
  CONTENT_DESCRIPTION: "Content Description",
  DEVELOPMENT_STAGE: "Development Stage",
  DONOR_DISEASE: "Donor Disease",
  EFFECTIVE_CELL_COUNT: "Cell Count Estimate",
  FILE_FORMAT: "File Format",
  FILE_NAME: "File Name",
  FILE_SIZE: "File Size",
  FILE_SOURCE: "File Source",
  GENUS_SPECIES: "Genus Species",
  INSTITUTION: "Institution",
  INSTRUMENT_MANUFACTURER_MODEL: "Instrument Manufacturer Model",
  LABORATORY: "Laboratory",
  LIBRARY_CONSTRUCTION_METHOD: "Library Construction Method",
  MATRIX_CELL_COUNT: "Matrix Cell Count",
  MODEL_ORGAN: "Model Organ",
  MODIFIED: "Modified",
  NUCLEIC_ACID_SOURCE: "Nucleic Acid Source",
  ORGAN_PART: "Organ Part",
  PAIRED_END: "Paired End",
  PRESERVATION_METHOD: "Preservation Method",
  PROJECT: "Project",
  PROJECT_TITLE: "Project Title",
  PUBLICATION_TITLE: "Publication Title",
  SAMPLE_ENTITY_TYPE: "Sample Type",
  SAMPLE_ID: "Sample Id",
  SAMPLE_TYPE: "Sample Type",
  SELECTED_CELL_TYPE: "Selected Cell Type",
  SPECIMEN_DISEASE: "Specimen Disease",
  SPECIMEN_ORGAN: "Anatomical Entity",
  WORKFLOW: "Analysis Protocol",
};
