import { NETWORK_KEYS } from "./constants";

/**
 * Set of possible metadata keys.
 */
export enum METADATA_KEY {
  ANATOMICAL_ENTITY = "ANATOMICAL_ENTITY",
  BIONETWORK_NAME = "BIONETWORK_NAME",
  BIOSAMPLE_TYPE = "BIOSAMPLE_TYPE",
  CONSENT_CODE = "CONSENT_CODE",
  CONTENT_DESCRIPTION = "CONTENT_DESCRIPTION",
  DATA_MODALITY = "DATA_MODALITY",
  DATA_TYPE = "DATA_TYPE",
  DATASET_NAME = "DATASET_NAME",
  DBGAP_ID = "DBGAP_ID",
  DEVELOPMENT_STAGE = "DEVELOPMENT_STAGE",
  DIAGNOSIS = "DIAGNOSIS",
  DISEASE_DONOR = "DISEASE_DONOR",
  DISEASE_INDICATION = "DISEASE_INDICATION",
  DISEASE_SPECIMEN = "DISEASE_SPECIMEN",
  DISEASE_STATUS_DONOR = "DISEASE_STATUS_DONOR",
  DISEASE_STATUS_SPECIMEN = "DISEASE_STATUS_SPECIMEN",
  FILE_FORMAT = "FILE_FORMAT",
  FOCUS_DISEASE = "FOCUS_DISEASE",
  LIBRARY_CONSTRUCTION_APPROACH = "LIBRARY_CONSTRUCTION_APPROACH",
  LIBRARY_PREPARATION = "LIBRARY_PREPARATION",
  MODEL_ORGAN = "MODEL_ORGAN",
  NUCLEIC_ACID_SOURCE = "NUCLEIC_ACID_SOURCE",
  ORGAN_PART = "ORGAN_PART",
  ORGANISM_AGE = "ORGANISM_AGE",
  ORGANISM_TYPE = "ORGANISM_TYPE",
  PHENOTYPIC_SEX = "PHENOTYPIC_SEX",
  PLATFORM = "PLATFORM",
  REPORTED_ETHNICITY = "REPORTED_ETHNICITY",
  SAMPLE_ID = "SAMPLE_ID",
  SAMPLE_TYPE = "SAMPLE_TYPE",
  SELECTED_CELL_TYPE = "SELECTED_CELL_TYPE",
  SPECIES = "SPECIES",
  STUDY = "STUDY",
  STUDY_DESIGN = "STUDY_DESIGN",
  WORKFLOW = "WORKFLOW",
  WORKSPACE_NAME = "WORKSPACE_NAME",
}

export interface Network {
  key: NetworkKey;
  name: string;
}

export type NetworkKey = (typeof NETWORK_KEYS)[number];

/**
 * Set of possible summary counts and other summary values as part of summary response.
 */
export enum SUMMARY {
  BIOSAMPLES = "BIOSAMPLES",
  DONORS = "DONORS",
  ESTIMATED_CELLS = "ESTIMATED_CELLS",
  FILE_FORMATS = "FILE_FORMATS",
  FILES = "FILES",
  SPECIES = "SPECIES",
  SPECIMENS = "SPECIMENS",
}
