#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd explorer

echo '🏗️👷 Checking your project before committing'

# Check Prettier
npm run check-format ||
(
    echo '🤔 Prettier Check Failed. Run npx prettier --write . try commit again.';
    false;
)

# Check ESLint
npm run lint ||
(
        echo '🤔  ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)


echo '✅✅✅✅ Looks good! Ship it!'