export const environment = {
    production: true,
    atlas: "lungmap",
    dataURL: "https://service.dev.singlecell.gi.ucsc.edu",
    defaultCatalog: "lm2",
    browserURL: "https://data-browser.dev.lungmap.net",
    googleOAuthClientId: "",
    portalURL: "https://data-browser.dev.lungmap.net",
    projectMetaURL: "https://dev.singlecell.gi.ucsc.edu",
    terraExportURL: "https://bvdp-saturn-dev.appspot.com",
    terraURL: "",
    title: "LungMAP Data Browser",
    deployment: "lungmap-dev",
    zendeskURL: "",
};
