export const environment = {
    production: true,
    atlas: "hca",
    dataURL: "https://service.azul.data.humancellatlas.org",
    defaultCatalog: "dcp20",
    browserURL: "https://data.humancellatlas.org",
    googleOAuthClientId: "",
    portalURL: "https://data.humancellatlas.org",
    projectMetaURL: "https://data.humancellatlas.org",
    terraExportURL: "https://app.terra.bio",
    terraURL: "",
    title: "HCA Data Browser",
    deployment: "dcp2",
    zendeskURL: "https://support.terra.bio",
};
