export const environment = {
    production: true,
    atlas: "hca",
    dataURL: "https://service.dev.singlecell.gi.ucsc.edu",
    defaultCatalog: "dcp2",
    browserURL: "https://ux-dev.singlecell.gi.ucsc.edu",
    googleOAuthClientId: "",
    portalURL: "https://ux-dev.singlecell.gi.ucsc.edu",
    projectMetaURL: "https://ux-dev.singlecell.gi.ucsc.edu",
    terraExportURL: "https://bvdp-saturn-dev.appspot.com",
    terraURL: "https://sam.dsde-dev.broadinstitute.org",
    title: "HCA Data Browser",
    deployment: "cgl-ux-dev",
    zendeskURL: "https://support.terra.bio",
};
