# CHANGE THESE VALUES TO GENERATE NEW REPORTS
# The date of the current month to report on (yyyy-mm)
CURRENT_MONTH = "2026-04"

ANVIL_CATALOG_ID = "368661710"
# Filter to exclude the Data Explorer
SECRET_NAME = "ANVIL_ANALYTICS_REPORTING_CLIENT_SECRET_PATH"
ANALYTICS_START = "2023-05-01"
HISTORIC_UA_DATA_PATH = "users_over_time_history.json"

OAUTH_PORT = 8082
