title: HCA DCP Analytics Report
author: "Hunter Craft, Dave Rogers, Mim Hastie and the HCA DCP Team"

execute:
  execute_notebooks: force

sphinx:
  recursive_update: true
  config:
    execution_timeout: 120
    html_show_copyright: false

exclude_patterns: [data-analytics.ipynb]
