/**
 * Action Types
 */
const REQUEST_FILE_SUMMARY = "REQUEST_FILE_SUMMARY";
const RECEIVE_FILE_SUMMARY = "RECEIVE_FILE_SUMMARY";
const REQUEST_FILE_FACETS = "REQUEST_FILE_FACETS";
const RECEIVE_FILE_FACETS = "RECEIVE_FILE_FACETS";
const RECEIVE_FILE_FILTERS = "RECEIVE_FILE_FILTERS";
const SELECT_FILE_FILTER = "SELECT_FILE_FILTER";
const RECEIVE_FILE_MANIFEST_SUMMARY = "RECEIVE_FILE_MANIFEST_SUMMARY";
const REQUEST_FILE_MANIFEST_SUMMARY = "REQUEST_FILE_MANIFEST_SUMMARY";
const REQUEST_DOWNLOAD_FILE_MANIFEST = "REQUEST_DOWNLOAD_FILE_MANIFEST";
const RECEIVE_DOWNLOAD_FILE_MANIFEST = "RECEIVE_DOWNLOAD_FILE_MANIFEST";
const REQUEST_KEYWORDS_QUERY = "REQUEST_KEYWORDS_QUERY";
const RECEIVE_KEYWORDS_QUERY = "RECEIVE_KEYWORDS_QUERY";
const CLEAR_KEYWORDS_QUERY = "CLEAR_KEYWORDS_QUERY";

export const ACTIONS = {
    REQUEST_FILE_SUMMARY,
    RECEIVE_FILE_SUMMARY,

    REQUEST_FILE_FACETS,
    RECEIVE_FILE_FACETS,

    RECEIVE_FILE_FILTERS,
    SELECT_FILE_FILTER,

    REQUEST_FILE_MANIFEST_SUMMARY,
    RECEIVE_FILE_MANIFEST_SUMMARY,
    REQUEST_DOWNLOAD_FILE_MANIFEST,
    RECEIVE_DOWNLOAD_FILE_MANIFEST,

    REQUEST_KEYWORDS_QUERY,
    RECEIVE_KEYWORDS_QUERY,
    CLEAR_KEYWORDS_QUERY
};
