/**
 * Action Types
 */
const REQUEST_FILE_SUMMARY = "REQUEST_FILE_SUMMARY";
const FILE_SUMMARY_RECEIVED = "FILE_SUMMARY_RECEIVED";

const FILE_FACETS_REQUESTED = "FILE_FACETS_REQUESTED";
const FILE_FACETS_RECEIVED = "FILE_FACETS_RECEIVED";

const INIT_FILE_FACETS = "INIT_FILE_FACETS";
const FILE_FACET_SELECTED = "FILE_FACET_SELECTED";

const RECEIVE_FILE_MANIFEST_SUMMARY = "RECEIVE_FILE_MANIFEST_SUMMARY";
const REQUEST_FILE_MANIFEST_SUMMARY = "REQUEST_FILE_MANIFEST_SUMMARY";

const REQUEST_DOWNLOAD_FILE_MANIFEST = "REQUEST_DOWNLOAD_FILE_MANIFEST";
const RECEIVE_DOWNLOAD_FILE_MANIFEST = "RECEIVE_DOWNLOAD_FILE_MANIFEST";

const REQUEST_KEYWORDS_QUERY = "REQUEST_KEYWORDS_QUERY";
const RECEIVE_KEYWORDS_QUERY = "RECEIVE_KEYWORDS_QUERY";

const CLEAR_KEYWORDS_QUERY = "CLEAR_KEYWORDS_QUERY";
const CLEAR_SELECTED_FACET = "CLEAR_SELECTED_FACET";

const FILE_FACET_METADATA_SUMMARY_REQUESTED = "FILE_FACET_METADATA_SUMMARY_REQUESTED";
const FILE_FACET_METADATA_SUMMARY_RECEIVED = "FILE_FACET_METADATA_SUMMARY_RECEIVED";


export const ACTIONS = {
    REQUEST_FILE_SUMMARY,
    FILE_SUMMARY_RECEIVED,

    FILE_FACETS_REQUESTED,
    FILE_FACETS_RECEIVED,

    INIT_FILE_FACETS,
    FILE_FACET_SELECTED,

    REQUEST_FILE_MANIFEST_SUMMARY,
    RECEIVE_FILE_MANIFEST_SUMMARY,
    REQUEST_DOWNLOAD_FILE_MANIFEST,
    RECEIVE_DOWNLOAD_FILE_MANIFEST,

    REQUEST_KEYWORDS_QUERY,
    RECEIVE_KEYWORDS_QUERY,
    CLEAR_KEYWORDS_QUERY,
    CLEAR_SELECTED_FACET,

    FILE_FACET_METADATA_SUMMARY_REQUESTED,
    FILE_FACET_METADATA_SUMMARY_RECEIVED
};
