/**
 * Action Types
 */
const RECEIVE_REPOSITORY_SUMMARY = "RECEIVE_REPOSITORY_SUMMARY";
const RECEIVE_REPOSITORY_FILES = "RECEIVE_REPOSITORY_FILES";

export const ACTIONS = {
    RECEIVE_REPOSITORY_SUMMARY,
    RECEIVE_REPOSITORY_FILES
};