on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual triggering

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          config-file: release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
