name: Playwright Tests anvil-cmg
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.15.1"
      - name: Install dependencies
        run: |
            cd explorer
            npm ci
      - name: Install Playwright Browsers
        run: |
            cd explorer
            npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd explorer
          npm run test:anvil-cmg
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30