name: Test build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: clevercanary/ng-cli-karma-python3:13.2.5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
      - run: |
          cd spa
          npm -v
          node -v
          npm ci
          ng test --watch=false
